### ISSUE TITLE
Under new management

### ISSUE THREAD

**Issue by eemeli** [eemeli/yaml-loader#26]
Hi, everyone.

@okonet has kindly agreed to transfer this repo to me, as he does not have the time to maintain it. I maintain the [yaml](https://www.npmjs.com/package/yaml) npm package, and my intent is to port this loader to use that, and make its options available to the loader.

As `yaml` supports all of the YAML spec that `js-yaml` supports (and more), and this loader does not currently expose any options, this change should be completely transparent to almost all users. It's possible that `js-yaml` has been parsing some invalid YAML as actually valid, so I can't guarantee that absolutely everything will work as previously.

I'll also be addressing the existing issues and PRs shortly.

**Comment by jhonnymichel** [comment]
Do we have a NPM Package for this?

the yaml-loader on NPM is this https://github.com/nkt/yml-loader repository, based on a different implementation, right?

**Comment by eemeli** [comment]
The corresponding npm package for this repo is [`yaml-loader`](https://www.npmjs.com/package/yaml-loader), but I don't have access to that at least yet.

**Comment by okonet** [comment]
@eemeli what's your npm username?

**Comment by okonet** [comment]
nevermimdn, npm invite UI wasn't able to clear the trailing whitespce

**Comment by okonet** [comment]
I've invited you so you should be able to publish it. That being said, I'd setup an automatic release process.

**Comment by eemeli** [comment]
Excellent! I'll look into getting a new version out soon, hopefully by the end of the week.

**Comment by eemeli** [comment]
Forgot to mention it here, but I released [version 0.6.0](https://github.com/eemeli/yaml-loader/releases/tag/v0.6.0) about two weeks ago. It should be backwards-compatible with hopefully all or nearly all real-world uses of the loader.

Future updates of the library are likely to be actual breaking changes, e.g. changing the output from stringified JSON to JS, which will eventually allow for e.g. YAML files containing circular references to be loaded correctly.
