### ISSUE TITLE
yaml v2.x support

### ISSUE THREAD

**Issue by caseyjhol** [eemeli/yaml-loader#34]
Are there plans to switch to yaml v2.x internally? If so, what does the timeline look like? Thanks!

**Comment by eemeli** [comment]
Eventually, sure.  No really clear timeline, at least yet. Do you have a use case for wanting a loader that uses `yaml@2` internally?

**Comment by caseyjhol** [comment]
Nothing major currently; I mainly wanted to set `logLevel: 'error'` to silence warnings.
