### ISSUE TITLE
Do no support vue-cli 4.x?

### ISSUE THREAD

**Issue by chenxin9482** [eemeli/yaml-loader#39]
I create a empty project for test yaml-load that use @vue/cli 4.5.11, but error:

![1627171692(1)](https://user-images.githubusercontent.com/65519955/126883733-68fd26a6-8512-4cfe-b764-4865d61214d1.jpg)

**Comment by eemeli** [comment]
That looks like your loader config is matching JS files to be loaded and parsed as YAML. If you'd like some more specific analysis, a minimal reproduction is probably required.

**Comment by chenxin9482** [comment]
Sorry, i can't understand. How to solve the problem? Can u give me a loader config for vue-cli 4.x

**Comment by eemeli** [comment]
As I try to explain in my previous comment, it's not really possible to solve your problem without first being able to replicate it. This means either a repo that you set up that shows this error bring generated, or other exact instructions for how to recreate the issue.

**Comment by chenxin9482** [comment]
emm..I think I need resolve 'fs' module in node.js for webpack, can i do that?

**Comment by eemeli** [comment]
Closing, as this really does not look like an actual issue with yaml-loader. You may want to seek assistance elsewhere for vue issues.
