### ISSUE TITLE
Prevent big file generation

### ISSUE THREAD

**Issue by theArtechnology** [eemeli/yaml-loader#42]
I included a yaml, with 10 elements in array, it is around 15KB, but when I manually convert the yaml to json plus getting the size, it is just a couple of bytes. Is there a way to reduce it to it's natural json size ?

**Comment by eemeli** [comment]
Not really sure what might be happening here. Could you share a minimal reproduction of what you're seeing to help diagnose the issue?

**Comment by theArtechnology** [comment]
Managed to fixed it, it was on my side, it had lots of white spaces in the yaml

**Comment by theArtechnology** [comment]
Thank you for this package :)
