### ISSUE TITLE
Changing 0.6.0 to 0.7.0 lead to `Module parse failed` error with `type: 'json'`

### ISSUE THREAD

**Issue by JonasDoe** [eemeli/yaml-loader#46]
After upgrading to from `v0.6.0` to `v0.7.0` (or `v0.8.0`) the compilation of my project fails with
```
./src/entity/descriptions/index.yml
Module parse failed: Unexpected token e in JSON at position 0 while parsing near 'export default {desc...'
File was processed with these loaders:
 * ./node_modules/yaml-loader/index.js
You may need an additional loader to handle the result of these loaders.
SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export default {desc...'
    at JSON.parse (<anonymous>)
```
, with the loaded `index.yml` looking like this:
```yaml
descriptionFiles:
    - account.yml
    - agent.yml
    - content.yml
```
It's a TypeScript project and I import the file with `const { descriptionFiles } = require('./descriptions/index.yml');`
I figure it's related to `type: 'json'` in the config which is required to run the project:
```javascript
module.exports = {
    mode: 'development',
    entry: './src/index.ts',
    module: {
        rules: [
            {
                test: /\.ya?ml$/,
                use: 'yaml-loader',
                type: 'json'
            }
        ]
    }
}
```

No idea whether it's an error on my side or there's something faulty - I'm not really an expert on webpack. So I apologize if the yaml-loader isn't responsible for that behavior.

**Comment by eemeli** [comment]
Please see the [asJSON option](https://github.com/eemeli/yaml-loader#asjson) to change the output if you need to continue using `type: 'json'`, or drop that from your loader config if using `yaml-loader@0.7.0` or later.

For more information, it's always good to check the [release notes](https://github.com/eemeli/yaml-loader/releases) when updating.

**Comment by JonasDoe** [comment]
Thanks for the reply!
Actually, I've checked the release note but the only thing I saw was "Output JavaScript source by default, rather than JSON", which reads for me as if I had opted for json before, I should just continue doing so - there's a new default I'm overriding.
Similary, I seem to miss something regarding the `asJson` option. From my understanding I have to set it to `type: "json"` (as before). Or is the option now called `asJson`?

**Comment by eemeli** [comment]
There are two different bags of options here. In the loader config, you may tell Webpack with `type: 'json'` that the loader you're using is emitting JSON rather than JS content. If you do that, you also need to include `options: { asJSON: true }` so that `yaml-loader` also knows to emit JSON rather than JS content.

**Comment by JonasDoe** [comment]
Yes, that did the trick! Thanks for the patience and the clarification!
