### ISSUE TITLE
Using with commonjs and webpack 5: Inline loader works but not webpack config

### ISSUE THREAD

**Issue by s6mike** [eemeli/yaml-loader#53]
Inline loader worked, though I had to use this default: config syntax: `{ default: config } = require('yaml-loader!../../config-mapjs.yml')` 

I don't quite understand why I had to use this {default: } format, it was a chatGPT suggestion, it said the file was being returned as a function.

I'd prefer to configure the loader in webpack. I've tried this config:

```
module: {
			rules: [
				{
					test: /\.ya?ml$/,
					use: 'yaml-loader',
				},
...
```

Then this line of code throws an error: config  = require('../../config-mapjs.yml'),

The problem seems to be that it's not using the loader:

```
[webpack-dev-server] ERROR in ./src/config-mapjs.yml 3:1
Module parse failed: Unexpected character '#' (3:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| ---
| 
> ########
| # MAPJS config data
| # To be used by js, lua filters and pandoc templates

```

It's clearly trying to access the correct file, and since it worked inline it looks like it's my webpack.config.js which is set incorrectly. Does it need to be configured differently because I'm using CommonJS?

**Comment by eemeli** [comment]
I'm not really sure what might be going on with your config, but the loader definitely works with Webpack v5. To validate that, I just added a couple of end-to-end tests with the latest version.

**Comment by s6mike** [comment]
The README instructions are for importing the YAML as an ES module. So I thought me using CommonJS might be the issue. It looks like the issue is that the yaml loader is not even being used for my YAML file.

I'm assuming that me using CommonJS require is why I have to use {default: config} to access the YAML data through the inline loader.

So I thought I might be missing something with configuring webpack loader rules for CommonJS too. I'm not that familiar with loaders so not sure if my configuration is the problem.

**Comment by eemeli** [comment]
With the default options, the loader turns a YAML file into an ES module, using `export default ...`. The way that Webpack v5 transpiles this to CommonJS means that the result of a `require('...yaml')` is an object `{ default: ... }`.

If you really want to avoid the `default` and your input data doesn't include referential loops, you can use the `asJSON: true` option to output JSON instead, which won't have that in CommonJS.

**Comment by s6mike** [comment]
Ah ok, that makes sense, thanks.

What I'm really getting at is - does this also mean that when I configure the loader in webpack.config.js, I need to do it differently to your README instructions, because I'm using CommonJS? I though that might be why it isn't working for me.

**Comment by eemeli** [comment]
No, the recommended config should work. If you'd like further assistance, providing a minimal reproduction of your specific problem would be a good next step.

**Comment by s6mike** [comment]
Well I feel stupid. What it has taken me an incredibly long time to realise is that all/most of the webpack config changes doesn't take effect until the webpack server is stopped and then started again. Webpack was rebuilding when I mde change so I assumed that it was using the new loader settings.

So the above all works once I've restarted the server. Unfortunately I didn't try that the first time round.
