### ISSUE TITLE
Security updates planned ? 

### ISSUE THREAD

**Issue by laurent-d** [eemeli/yaml-loader#55]
Hi @eemeli and thanks for this awesome lib, 
Did you plan to update yaml dependency to : 2.2.2 ?

**Comment by eemeli** [comment]
There should be no need for that, as the caret range includes the fixes. Furthermore, there is no security concern for the usage in this library, as it does not rely on the `parseDocument()` call never throwing errors.

**Comment by laurent-d** [comment]
Thanks for the information @eemeli !!
