### ISSUE TITLE
update yaml library

### ISSUE THREAD

**Issue by EddyYeung1** [eemeli/yaml-loader#58]
any chance you could update your yaml library? 

Getting this dependabot alert
<img width="943" alt="Screenshot 2024-03-13 at 12 10 47 PM" src="https://github.com/eemeli/yaml-loader/assets/26090238/6af10e93-4e5b-41ad-a97e-408ba49f46af">

**Comment by eemeli** [comment]
The `yaml` dependency here is `^2.0.0`, which includes 2.2.2 and later. Try clicking on the "Try again" button?

**Comment by EddyYeung1** [comment]
gives me the same error

**Comment by eemeli** [comment]
This seems like an issue with dependabot rather than this package.
